#!/usr/bin/env python

import sys
sys.path.append("../")

import graphene
from libgql import create_module

class User(graphene.ObjectType):
    name = graphene.String()

    def resolve_name(self, info):
        return "Hello World"

class Query(graphene.ObjectType):
    current_user = graphene.Field(User)

    def resolve_current_user(self, info):
        return User()

schema = graphene.Schema(query=Query)

create_module(schema)

