#!/usr/bin/env node

const { createModule } = require("../");
const {
  makeExecutableSchema,
  addMockFunctionsToSchema
} = require("graphql-tools");

const user = {
  name: "Joe User",
  lists: [{ note: "a list item" }]
};

const schema = makeExecutableSchema({
  typeDefs: `
      type TodoListItem {
        author: User!
        note: String!
        list: TodoList
      }

      type User {
        name: String!
        lists: [TodoList]
      }

      type TodoList {
        name: String
        items: [TodoListItem]
      }

      type Query {
        currentUser: User
      }
    `
});

addMockFunctionsToSchema({ schema });

module.exports = createModule(schema);
